In [1]:
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelBinarizer

In [2]:
#define example
data=['cold','hot','cold','hot','cold','hot','cold','warm','cold','warm','warm']
values=array(data)
print('data:',values)

#integer encode
label_encoder=LabelEncoder()
integer_encoded=label_encoder.fit_transform(values)
print('Label Encoder:',integer_encoded)

#onehot encode
onehot_encoder=OneHotEncoder(sparse=False)
integer_encoded=integer_encoded.reshape(len(integer_encoded),1)
onehot_encoded=onehot_encoder.fit_transform(integer_encoded)
print('Onehot Encoder:',onehot_encoded)

#binary encoded
lb=LabelBinarizer()
print('Label Binarizer',lb.fit_transform(values))

data: ['cold' 'hot' 'cold' 'hot' 'cold' 'hot' 'cold' 'warm' 'cold' 'warm' 'warm']
Label Encoder: [0 1 0 1 0 1 0 2 0 2 2]
Onehot Encoder: [[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
Label Binarizer [[1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 1]]


In [3]:
values=values.reshape(len(values),1)
onehot_encoder.fit_transform(values)

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])